### ISSUE TITLE
How do you connect to a remote streaming server?

### ISSUE THREAD

**Issue by natiki** [nats-io/csharp-nats-streaming#104]
Hi,

```
using (IStanConnection c = cf.CreateConnection("test-cluster", ClientId)
```
When creating a conenction to the server, how do you do so when the client and the server are on two different machines? CrateConnection() only appears to offer the ability to offer a ClusterId as a means of connection. How do you specify a remote IP Address?

**Comment by ColinSullivan1** [comment]
@natiki , thank you for using NATS!  

You'll want to use the `StanConnectionFactory.CreateConnection(clusterID, clientID, options)` API.

There are two ways, both require setting options when creating the connection.  First, you can create a NATS connection, then set that in options using the [STAN.Client.StanOptions.NatsConn](http://nats-io.github.io/csharp-nats-streaming/class_s_t_a_n_1_1_client_1_1_stan_options.html#a7119c66f161f0f7e37ba9ac17e1ca7d5) property.  This is required if you will someday use TLS, you can find more on that (and passing options) [here](https://github.com/nats-io/csharp-nats-streaming#enabling-tls).

Alternatively, you can set the URL in [ STAN.Client.StanOptions.NatsURL](http://nats-io.github.io/csharp-nats-streaming/class_s_t_a_n_1_1_client_1_1_stan_options.html#a4e1d48154771277eb82fed3d3274a044).

**Comment by natiki** [comment]
Hi @ColinSullivan1 ,

Much appreciated. That sorted me out.
