### ISSUE TITLE
NATSTimeoutException in combination with PureWebsocket

### ISSUE THREAD

**Issue by senzacionale** [nats-io/csharp-nats-streaming#109]
If I want to use PureWebSocket (https://github.com/Coinigy/PureWebSockets) and OnMessage send messages to nats sreaming I am always getting NATSTimeoutException  exception in this code:
```

try
            {
                cr = nc.Request(discoverSubject,
                    ProtocolSerializer.marshal(req),
                    opts.ConnectTimeout);
            }
            catch (NATSTimeoutException)
            {
                protoUnsubscribe();
                throw new StanConnectRequestTimeoutException();
            }
```

Can I use nats-streaming when I get message from web socket?

**Comment by ColinSullivan1** [comment]
@senzacionale , The NATS servers do not support web socket connections at this time.  It's on the roadmap, but planned for the second half of 2019.

**Comment by senzacionale** [comment]
I do not want to use websocket connections for Nats. I just want to use Nats inside wed events as multithreading. 

Thank you
