### ISSUE TITLE
Should Timestamp of messages be in UTC Format?

### ISSUE THREAD

**Issue by bkim54** [nats-io/csharp-nats-streaming#14]
Hi, I was looking through the StanMsg.cs file and noticed that the received timestamp of the message gets constructed like this 
` return new DateTime(1970, 1, 1, 0, 0, 0, 0)`
but according to msdn documentation this results in an 'unspecified' DateTimeKind, should it be set to
`new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)`?

**Comment by ColinSullivan1** [comment]
@bkim54:  Thanks, I'll look into it.

**Comment by ColinSullivan1** [comment]
@bkim54 Fixed - Thanks for creating the issue!
