### ISSUE TITLE
get current max sequence number for a topic.

### ISSUE THREAD

**Issue by bkim54** [nats-io/csharp-nats-streaming#21]

**Comment by ColinSullivan1** [comment]
@bkim54 Thank you for opening this.  This is related to https://github.com/nats-io/nats-streaming-server/issues/175.

**Comment by ColinSullivan1** [comment]
Closing this issue as part of housekeeping.  Moving forward, this will be addressed by  https://github.com/nats-io/nats-streaming-server/issues/175.
