### ISSUE TITLE
Add Client Support for Subscription.Close()

### ISSUE THREAD

**Issue by sfrooster** [nats-io/csharp-nats-streaming#27]
This is/will be supported in the Server, needs to be implemented in the Client:

https://github.com/nats-io/nats-streaming-server/issues/182

**Comment by ColinSullivan1** [comment]
Thanks for opening the issue.  It's on my plate.

**Comment by ColinSullivan1** [comment]
For tracking, here are the parallel go client commits:  

https://github.com/nats-io/go-nats-streaming/pull/115
https://github.com/nats-io/go-nats-streaming/pull/123
