### ISSUE TITLE
Publish Acks always timeout

### ISSUE THREAD

**Issue by anjelinio** [nats-io/csharp-nats-streaming#28]
Hi guys, I'm facing the exact same issue described earlier at:

https://github.com/nats-io/csharp-nats-streaming/issues/13

I've already tried raising my timeout limit to 30 secs, and max pubs in flight to around 30K. That resulted in the timeouts happening later, exactly at 30K messages sent. 

I know I am publishing too fast, actually I'm publishing 1.5 million messages in a loop as fast as I can, but .. this is a streaming server that should handle the load, right [?] 

- Also, this behavior doesn't change even if I Thread.Sleep(...) for 50millis between publishing messages.  It seems that no Acks are returned to the publisher whatsoever though, as soon as it reaches the "InFlight" limit it breaks down. Not a single Ack returned. 

This is the code that initializes my connection: 

var opts = StanOptions.GetDefaultOptions();
            opts.PubAckWait = 30 * 1000;
            opts.MaxPubAcksInFlight = 32 * 1000;

            return _connectionFactory.CreateConnection("test-cluster", clientID ?? Guid.NewGuid().ToString(), opts);

And then, my publisher uses that connection like so:

this.Connection.Publish(base.Topic, ObjectToByteArray(message));

Could it be that I'm doing something wrong ?

=============== Edit ============================ 

After some more searching & poking around, I used the publish overload that also accepts an Ack event handler, to get a better idea of what is going on exactly. 

Now, acks return, but the code now blocks until an Ack is received or while the not Ack-ed limit has been reached [ ? _not really sure which right now_ ]. 

In any case, messages now seem to get through, but I sometimes get 1 failure and 2 success callbacks for a single message. Seems like when a pub times-out, I will get one failure and two success Acks immediately after that, and that seems to be "the" behavior.

Is all this normal ? Is this the throughput I should be expecting overall ? Right now I guess posting 500 simple small string messages seems to require something like half an hour to complete !
( I'm just posting "Test message N" right now mind you )

Thanks a lot,
Angelo

**Comment by ColinSullivan1** [comment]
@anjelinio , 

Thank you for using NATS!

The ack behavior seems unusual, I'll take a look.

As far as performance goes, 1.5 million msgs a second is a lot for a NATS streaming server - you're very likely hitting some limits (disk/cpu/memory).  You could be swapping memory which will really impact performance.  That being said, 500 small messages shouldn't take that long to produce, you should normally be able to publish between 50-250k messages per second, depending on hardware.

I'll run some tests on my own - in the meantime, would you have test code that reproduces this issue?

Thanks,
Colin

**Comment by ColinSullivan1** [comment]
One thought - using a new client ID for each test will result in the NATS streaming server is persisting the data for each test run.  This will have an additional memory/disk impact on the streaming server - as you run tests, you'll consume much more resources than using the same client ID (unless you are clearing out files and restarting the server for each test run).

**Comment by anjelinio** [comment]
Hey Collin, yeah, I run a few more tests on it, and I came to the same conclusion, that I'm hitting "some" limit at some point. The fact that I'm running the test on my development machine certainly won't help there too :P

I've played around with my test code, lowering/raising the number of consumers and no of messages published and it seems that the number of subscribers directly affects the server's behavior. With 6 listeners it seems that I can send up to 60K messages and everything works fine on this machine. I'll leave a test running to try and send a few million messages with a varying pause between messages to see how it goes and I'll return tomorrow with the results and my test project. 

 For the record, I'm running on a 4-core i7 @ 3.4Ghz, 8Gb RAM and an SSD hd, with a bunch of servers and apps running at the same time. I can see why the server could get .. confused :P 

Still, some sort of error message would be nice when we start loosing messages if its possible

Thanks a lot,
Angelo

**Comment by ColinSullivan1** [comment]
@anjelinio , I merged PR https://github.com/nats-io/csharp-nats-streaming/pull/29 into master, which should resolve the issue you are seeing with the timeouts.

Thanks,
Colin

**Comment by anjelinio** [comment]
Thanks Collin, I'll try it out asap. I should tell you that the same applies to the non-streaming NATS server too. In my test it has to do with the number of listeners on my channel. Anything above 7 listeners is guaranteed to fail on my system. 

I'm using the C# client, compiled for .NET 4.0 if you need to, I can send you a zip with my test project

**Comment by ColinSullivan1** [comment]
@anjelinio - How fast are you publishing when you are seeing this with non-streaming NATS?  If publishing as fast as possible, I'm still thinking you're likely running into hardware/os resource issues....  At a moderate rate, it's not out of reach for an application to support thousands of subscribers.

**Comment by anjelinio** [comment]
Same test, as fast as I can. I also tried another test where I pause some random amount of time between sending messages  - anything between 0 and 30 secs - which works much better indeed, but I can't really confirm the "thousands" part with many messages. Unfortunately I only got a single dev machine here and I need it to work. 

I'll leave it running tonite with something like 1000 consumers and a few thousand messages with variable delay between sends and I'll let you know how it went.

**Comment by ColinSullivan1** [comment]
OK, I'll look forward to your results!  

A few things for your test:
* The NATS server will cut off slow subscribers as a protection mechanism to ensure it's own availability, so you may encounter slow subscriber errors resulting in a dropped connection in your test if publishing faster than your application can consume.
* If you are using 1000 consumers (subscribers), I'd suggest setting the [SubscriberDeliveryTaskCount](http://nats-io.github.io/csharp-nats/class_n_a_t_s_1_1_client_1_1_options.html#a030dfa5eac04072735d7529147d5c562) option.  A value of 50 might be a good place to start with in your test, but you may need to experiment a bit to discover what works best in your environment.

**Comment by anjelinio** [comment]
Mornin' Collin. 

I've run my little test last night, settings were 1000 messages published with variable delay 0 - 15 secs, for 200 subscribers, total 200K messages to be delivered. In my test I wait for noOfMessages * 1min for delivery before I exit and print out some results. 

I found it still running this morning ( lol, 200K mins is a lot of time apparently :D ), it had delivered around 199K of those messages, unfortunately I didn't count delivered messages per unique subscriber so I don't know whether it dropped some of them. ( I also don't know whether my naive multithreading has anything to do with the results ) 

I'm attaching a .rar with the test project in this message in any case. Also, its a .NET 4.0 solution, the NATS.Client.dll is compiled by me from the sources. This was run against the plain NATS server, not the streaming one.

**Comment by ColinSullivan1** [comment]
@anjelinio ,

Thank you for sharing your code.  I'm wondering if you are running into slow subscribers errors.  If a subscriber cannot keep up, the NATS server will disconnect a the client to protect itself.

I suggest adding some sort of notification in the various error handlers to see if you are getting disconnected (and thus missing messages), in your SLNet.Base.Messaging assembly.  If you set the NATS AsyncErrorEventHandler and DisconnectedEventHandler (described [here](https://github.com/nats-io/csharp-nats#advanced-usage)), you can find out in your application if that is happening.  The NATS server will also log output to this effect as well.  It's often useful to set a ClosedEventHandler as well.

For stress tests, you can increase the `NATS.Client.Options.SubChannelLength` to a very large value., here's an [example](https://github.com/nats-io/csharp-nats/blob/v0.7.0/examples/Benchmark/Benchmark.cs#L175), but I wouldn't necessarily recommend that for a typical application in production.

Hopefully with these we'll see your ```"Tremendous success !!! "``` message!   

Thanks,
Colin
