### ISSUE TITLE
After publisher reconnect to new server, messages not delivered to subscriber

### ISSUE THREAD

**Issue by vsundupey** [nats-io/csharp-nats-streaming#34]
please, check my fork
https://github.com/vsundupey/csharp-nats-streaming

**Comment by ColinSullivan1** [comment]
@vsundupey , Thank you - I'll take a look.

**Comment by ColinSullivan1** [comment]
@vsundupey , It looks like you are using two NATS streaming servers, an are publishing to only one.  The NATS streaming server is currently single node, so you should use one for your test.  I'd suggest starting with one connection, one subscriber, and one server to experiment with redelivery.  There are some examples in tests [here](https://github.com/nats-io/csharp-nats-streaming/blob/0.1.3/STAN.Client.UnitTests/UnitTestBasic.cs#L1107) and [here](https://github.com/nats-io/csharp-nats-streaming/blob/0.1.3/STAN.Client.UnitTests/UnitTestBasic.cs#L882).

Thank you for using NATS, and please feel free to ask any questions or provide comments.  Contributions are always welcome!
