### ISSUE TITLE
NuGet restore for .NET core

### ISSUE THREAD

**Issue by loremaps** [nats-io/csharp-nats-streaming#42]
Hi,

I get the following exception when trying to restore the NuGet package in an .NET Core project (VS2017):

> Restoring packages for D:\Projects\stanTest\stanTest\stanTest.csproj...
> Package STAN.Client 0.1.3 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package STAN.Client 0.1.3 supports: net45 (.NETFramework,Version=v4.5)
> Package NATS.Client 0.6.1 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package NATS.Client 0.6.1 supports: net45 (.NETFramework,Version=v4.5)
> One or more packages are incompatible with .NETCoreApp,Version=v1.1.
> Package restore failed. Rolling back package changes for 'stanTest'.

This should be working according to #37 correct? 

Thanks

**Comment by ColinSullivan1** [comment]
@loremaps , this is odd - It looks like the .NET 45 clients are being installed with core.  Have you tried clearing out your local NuGet cache before restoring?

 `nuget locals -Clear all`

**Comment by ColinSullivan1** [comment]
Ahh, I see the problem; .NET core is not available for NATS streaming in NuGet yet, only in master branch.  There will be release soon (I'm aiming for the next few days) where the latest streaming NuGet packages will have .NET core support.  In the meantime, it you [build](https://github.com/nats-io/csharp-nats-streaming#net-core) the NATS streaming client, you'll have .NET core support.

**Comment by loremaps** [comment]
Thank you for your prompt response. Indeed building the client works fine with .NET core. Looking forward for the latest NuGet packages.

**Comment by ColinSullivan1** [comment]
@loremaps You're welcome - I'm glad to hear it is working out for you!  The release is coming soon...
