### ISSUE TITLE
Connection fails when clusterId is anything but "test-cluster"

### ISSUE THREAD

**Issue by ThomasVestergaard** [nats-io/csharp-nats-streaming#56]
This works:
`var natsConnection = new StanConnectionFactory().CreateConnection("test-cluster", "something-else");`

This does not
 `var natsConnection = new StanConnectionFactory().CreateConnection("my-cluster", "something-else");`

Is this somehow tied to the configuration of the cluster or otherwise intended behaviour?

**Comment by ColinSullivan1** [comment]
@ThomasVestergaard , thanks for using NATS!

You'll want to match your cluster id connection param with what you use with the cluster ID (the `-cid` flag) of the NATS streaming server. The default is `test-cluster`.  You can find the NATS Streaming Server command line options [here](https://github.com/nats-io/nats-streaming-server#command-line-arguments).  

` -cid, --cluster_id  <string>      Cluster ID (default: test-cluster)`

**Comment by ThomasVestergaard** [comment]
@ColinSullivan1 No problem, it's an interesting project with a lot of great features already.

Great, I thought it might be something like that. I'll look at the server config.
You can close the issue.

Thanks!
