### ISSUE TITLE
Publish latest Nuget package version

### ISSUE THREAD

**Issue by manigandham** [nats-io/csharp-nats-streaming#57]
The nuget.org listing shows versions 0.1.4 from April 26, 2017: https://www.nuget.org/packages/STAN.Client/

It looks like there have been several commits since then, so can we get a new package published to Nuget?

**Comment by ColinSullivan1** [comment]
@manigandham , we can.  I'd like to do a few more things first... working on getting one out soon.

**Comment by manigandham** [comment]
@ColinSullivan1 Any update here? 

It really seems like the C# library is just neglected if it takes over 1 year to publish the latest changes...

**Comment by ColinSullivan1** [comment]
Unfortunately there is a lot of other work that keeps taking priority since there is revenue attached to it.  This is still on my plate, and I have much of the connection lost handler work implemented.  I am getting close to a release.

**Comment by ColinSullivan1** [comment]
Thank you for your patience, we've just released [v0.1.5](https://github.com/nats-io/csharp-nats-streaming/releases/tag/v0.1.5).
