### ISSUE TITLE
Which should I use csharp-nats or csharp-nats-streaming?

### ISSUE THREAD

**Issue by ttakahari** [nats-io/csharp-nats-streaming#59]
Hi.

I develop an application that sends messages to a NATS server with C#.

So, I look for NATS client library for C# and I find two libraries.
One of them is this repository and another is [here](https://github.com/nats-io/csharp-nats).

I'm confused because I don't know what is the difference.
Which library should I use and cloud you tell me what is the difference?

**Comment by ColinSullivan1** [comment]
@ttakahari , Thank you for using NATS!

if you are sending to a core NATS server (`gnatsd`) you'll want to use [csharp-nats](https://github.com/nats-io/csharp-nats).  This repository is the .NET client library for NATS streaming.

[NATS streaming](https://nats.io/documentation/streaming/nats-streaming-intro/) is another component of NATS used when you need to guarantee message delivery or replay old messages.

**Comment by ttakahari** [comment]
@ColinSullivan1 
Thank you for replying.
I find which libraty I should use and what is the difference.
I want my developing application to send message surely, so I will use csharp-nats-streaming.
