### ISSUE TITLE
Connection Lost Handler and error handling strategy.

### ISSUE THREAD

**Issue by ktamayop** [nats-io/csharp-nats-streaming#63]
Hey guys!

I've been playing around a little with the library. I'd love to hear your thoughts on the strategy I should use to gracefully  handle the errors when creating connections and other connectivity issues I might face. 

Looking at the golang client you can see a [ConnectionLostHandler](https://github.com/nats-io/go-nats-streaming/blob/e15a53f85e4932540600a16b56f6c4f65f58176f/stan.go#L105) function you can pass to the `Options` and take actions when any error happens. That is not present in this client at the moment. 

So here some questions:

1. Is this by design? 
2. Are you handling this internally to retry the connections? 
3. Should I handle the possible exceptions in my integration logic? 
4. What's the recommended approach/strategy?

Thanks in advance and keep up the good work!
Cheers,
Karel.

**Comment by ColinSullivan1** [comment]
Hi @ktamayop, thank you for looking at NATS!  

This is a relatively new feature to the go client and hasn't been ported into the C# client yet.  I'm hoping to implement this soon.  Underneath this library, core NATS will attempt to reconnect and will resubscribe if you lose network connectivity to the connected NATS server (which may be in your NATS streaming server process if you are running the embedded NATS server, the default behavior).

Today, you can create core NATS connection, setup a disconnected callback event handler in the underlying NATS connection, then then pass that into NATS streaming using the `Options.NatsConn` property.  An example of passing a core NATS connection can be found [here](https://github.com/nats-io/csharp-nats-streaming/blob/master/STAN.Client.UnitTests/UnitTestBasic.cs#L1607), and setting disconnected/reconnected event handlers in core NATS can be found [here](https://github.com/nats-io/csharp-nats/blob/master/NATSUnitTests/UnitTestReconnect.cs#L121).  The core NATS disconnected and reconnected events will notify you about your underlying connection to NATS, but doesn't cover the case when the NATS streaming server is not available when your client does have direct TCP connection (e.g. if your client is connected through another core NATS server in a cluster or running stand-alone).

This can be confusing, you can find more about the relationship between core NATS streaming and NATS streaming in ["Understanding NATS Architecture"](https://github.com/nats-io/roadmap/blob/master/architecture/ARCHITECTURE.md#streaming-server).

Does this make sense?

Thanks,
Colin

**Comment by ktamayop** [comment]
That makes perfect sense! I'll take a look at these promising stuffs ASAP. Thank you very much @ColinSullivan1.

Karel.

**Comment by ColinSullivan1** [comment]
Resolved with #101.
