### ISSUE TITLE
Version 0.1.5.0 nuget

### ISSUE THREAD

**Issue by anjmao** [nats-io/csharp-nats-streaming#76]
Hi, could you push 0.1.5.0 to nuget? I would like to use Protobuf 3.6. Thanks :)

**Comment by ColinSullivan1** [comment]
There are a few fixes in progress I'd like to get added first.  I realize this has been awhile.

**Comment by ColinSullivan1** [comment]
Thank you for your patience, we've just released [v0.1.5](https://github.com/nats-io/csharp-nats-streaming/releases/tag/v0.1.5).
