### ISSUE TITLE
Have to close IConnection manually when closing ISTANConnection

### ISSUE THREAD

**Issue by selstam** [nats-io/csharp-nats-streaming#79]
I saw some rogue connection on my NATS-server and they kept increasing in numbers.

I noticed that simply closing the ISTANConnection wouldn't unsubscribe the internal IConnection. I have to manually close the IConnection before closing the ISTANConnection to release the connection to my server.

```
_stanConnection.NATSConnection.Close();
_stanConnection.Close();
```

Even if i try to dispose the ISTANConnection the connection to the NATS server remains.

**Comment by ColinSullivan1** [comment]
Did you create a NATS connection yourself and pass it in through [StanOptions.NatsConn](http://nats-io.github.io/csharp-nats-streaming/class_s_t_a_n_1_1_client_1_1_stan_options.html#a7119c66f161f0f7e37ba9ac17e1ca7d5), or let the STAN API create it?

**Comment by selstam** [comment]
> Did you create a NATS connection yourself and pass it in through [StanOptions.NatsConn](http://nats-io.github.io/csharp-nats-streaming/class_s_t_a_n_1_1_client_1_1_stan_options.html#a7119c66f161f0f7e37ba9ac17e1ca7d5), or let the STAN API create it?

I created the NATS connection myself and passed it on to StanConnectionFactory().CreateConnection() ...

**Comment by ColinSullivan1** [comment]
@selstam , In that case, you'll need to close the connection you passed into the NATS streaming client.  The NATS streaming client won't close (or otherwise alter) a NATS connection passed to it.
