### ISSUE TITLE
Is this still viable?

### ISSUE THREAD

**Issue by ChristianSauer** [nats-io/csharp-nats-streaming#87]
Hello,
I am currently considering moving off RabbitMq due to the lack of good client libraries ( most assume that they will always talk to another c# client, which is not viable in our ecosystem).
But the lack of activity on this repro concerns me - it does not look like bugs gets fixed etc. I am kind of burned by the lack of development on the RawRabbit Client so I would like to know what your plans are?

Thanks!

**Comment by ColinSullivan1** [comment]
@ChristianSauer , Thanks for your interest in NATS!

Don't give up yet.  Admittedly, this repository hasn't been receiving the attention it needs lately - my role has changed over time and with our growing business at Synadia I cannot find as much time to devote to the C# repositories.  That being said, there has been ongoing development, albeit slowly (e.g. see the "pings" branch).

We're in the process of on-boarding another very solid contributor as an official NATS Maintainer to help with the NATS C# assemblies, and who will also hopefully also spur myself to dedicate more time here.

Please stay tuned.

**Comment by ColinSullivan1** [comment]
Thank you for your patience, we've just released v0.1.5

https://github.com/nats-io/csharp-nats-streaming/releases/tag/v0.1.5
