### ISSUE TITLE
NATSTimeoutException when we supply a non existing or wrong cluster id

### ISSUE THREAD

**Issue by Amardaya** [nats-io/csharp-nats-streaming#93]
Hi,
not sure if i m going to get my answer as i m not seeing a lot of activities around Nats Client using .net, 

while i m trying to use Nats streaming server i start getting a misleading exception ( NATSTimeoutException ) 

 at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at NATS.Client.Connection.request(String subject, Byte[] data, Int32 offset, Int32 count, Int32 timeout)

 when i provided a wrong cluster id , is this the intent or just triggering the wrong exception
Thanks

**Comment by ThomasVestergaard** [comment]
I have encountered this one as well and it can be somewhat difficult to track down if you are not aware of the importance of cluster id. However a NATSTimeoutException, IMO, is the correct exception. An error message saying that this coule be because if the IP/Hostname, Port OR cluster id might help narrowing this down earlier.

**Comment by ColinSullivan1** [comment]
This issue seems to be a common one.  Would something like a ClusterUnavailableException with the cluster name in the message sound reasonable?

**Comment by Amardaya** [comment]
thanks for your answers guys 
yes it make more sense to have an exception that contain a cluster as we need to separate exception between nats streaming connection (IStanConnection)  and nats connection (IConnection)  because nats connection doesn't really care about the cluster ID 
Thanks

**Comment by ColinSullivan1** [comment]
Hi all, I created a PR for this, #111 , does this look like it'll help?  After further thought, I didn't want to change the exception because that would be a breaking change in the API.

**Comment by Amardaya** [comment]
yes it will diffenetly help and better than the previous exception 
thanks Colin for this enhancement
