### ISSUE TITLE
StanMsgHandlerArgs internal constructor and no interface makes unit-testing impossible

### ISSUE THREAD

**Issue by kasperhhk** [nats-io/csharp-nats-streaming#94]
StanMsgHandlerArgs currently has an internal constructor, and it is not implementing an interface.
This makes it impossible to create unit-tests on methods that in some way rely on an object of this type.

Would it be possible for it to be opened up, or for there to be some factory that can produce a "default" version?

Edit: This also applies to StanMsg

**Comment by kasperhhk** [comment]
I noticed that other types, such as StanSubscriptionOptions, have a "GetDefaultOptions" static method, that produces a "default" object.
If this is added to StanMsgHandlerArgs and StanMsg, then it would be fine.

**Comment by BobyMoor** [comment]
+1 for StanConnectionFactory. Love the NATS and library, but it would be nice to have an option of unit testing.

**Comment by ColinSullivan1** [comment]
I think this is a reasonable request, will add this functionality.
