### ISSUE TITLE
Message redelivered even if already acknowledged

### ISSUE THREAD

**Issue by lorenzoisidori21** [nats-io/csharp-nats-streaming#96]
My subscriber can do long work. Sometimes they are greater than default ack wait time (30sec).
So I try to manually ack my message, doing like this:

`StanSubscriptionOptions sOpts = StanSubscriptionOptions.GetDefaultOptions();

            sOpts.ManualAcks = true;

            EventHandler<StanMsgHandlerArgs> msgHandler = (sender, args) =>

            {

                args.Message.Ack();

                Thread.Sleep(40000);

            };

            sOpts.DurableName = "my-durable";

            var s = c.Subscribe(subject, qGroup, sOpts, msgHandler);

`

In this code, subscriber does a work for 40sec.
If I send 2 messages, the second has always redelivered.
What is my mistake?

**Comment by ColinSullivan1** [comment]
The first message will be acknowledged as soon as it is received, so will not be resent.  If the second message is delivered to the client library and expires before it is processed by your callback, the NATS streaming server will redeliver it.  With a 30 second AckWait, and a 40 second delay, this is very likely to happen.

You can increase the AckWait through the [StanSubscriptionOptions.AckWait
](http://nats-io.github.io/csharp-nats-streaming/class_s_t_a_n_1_1_client_1_1_stan_subscription_options.html#a345ca6a37db6c5ab84c0b2cdac66688e) option, or [queue subscribe](http://nats-io.github.io/csharp-nats-streaming/interface_s_t_a_n_1_1_client_1_1_i_stan_connection.html#a04d9a7370dd48e8ca7f9db3c6d8a8cbc) and run multiple instances/subscribers to load balance your workload.  More on queue subscriptions can be found [here](https://nats.io/documentation/writing_applications/concepts/).

Feel free to re-open this if you have further questions.

**Comment by lorenzoisidori21** [comment]
Thank you @ColinSullivan1. The answer is clear and your solution, about to set the StanSubscriptionOptions.AckWait higher, works.
I misunderstood the purpose of manual ack and the subscriber's behaviour.

Now Subscriber behaviour is clear, but I still don't understand the sake of manual ack: when and why to use it?

Thank you in advance
